name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      steps:
        - uses: actions/checkout@v2
        - container: node
        run: echo "main"
